default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Smartr_Remastered_development

test:
  <<: *default
  database: Smartr_Remastered_test
  
production:
  <<: *default
  database: Smartr_Remastered_production
  username: Smartr_Remastered
  password: <%= ENV['SMARTR_REMASTERED_DATABASE_PASSWORD'] %>